// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAK6d-Kp-w-X37ORBBvQ9fV4F_lmdgruKU',
    appId: '1:555806693501:web:a72dce2533ee9a88de7914',
    messagingSenderId: '555806693501',
    projectId: 'proteka-app',
    authDomain: 'proteka-app.firebaseapp.com',
    storageBucket: 'proteka-app.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCHmPgRz-66tIX_PE0oQusC7WTXN9vEEUA',
    appId: '1:555806693501:android:bcf21887674a3d38de7914',
    messagingSenderId: '555806693501',
    projectId: 'proteka-app',
    storageBucket: 'proteka-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA9L2OhFdH0ewDvvEkklbcmWdsVdOYADD8',
    appId: '1:555806693501:ios:65777683a586dd67de7914',
    messagingSenderId: '555806693501',
    projectId: 'proteka-app',
    storageBucket: 'proteka-app.appspot.com',
    iosClientId: '555806693501-33clgg682shjik4e8pna2hseg36dnred.apps.googleusercontent.com',
    iosBundleId: 'com.example.protekaApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA9L2OhFdH0ewDvvEkklbcmWdsVdOYADD8',
    appId: '1:555806693501:ios:65777683a586dd67de7914',
    messagingSenderId: '555806693501',
    projectId: 'proteka-app',
    storageBucket: 'proteka-app.appspot.com',
    iosClientId: '555806693501-33clgg682shjik4e8pna2hseg36dnred.apps.googleusercontent.com',
    iosBundleId: 'com.example.protekaApp',
  );
}
